declare module '@mediapipe/segmentation';
declare module 'quantize';
declare module 'color.js';
declare module 'perspective-transform';
declare module '@mediapipe/tasks-vision';
declare module 'firebase/app';
declare module 'firebase/auth';
declare module 'firebase/firestore';
declare module 'firebase/analytics';
